name: Build Android APK with Buildozer
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev \
          libsqlite3-dev openjdk-17-jdk unzip zip autoconf automake libtool \
          pkg-config lld cmake matrixssl libpcre3-dev
        sudo apt-get install -y ffmpeg

    - name: Install Python Dependencies
      run: |
        pip install --upgrade pip virtualenv setuptools
        pip install cython==0.29.33
        pip install kivy plyer buildozer

    - name: Set Environment Variables
      run: |
        echo "APP_ANDROID_ARCHS=arm64-v8a" >> $GITHUB_ENV

    - name: Build Android APK
      run: |
        # স্বয়ংক্রিয়ভাবে অ্যান্ড্রয়েডের শর্তাবলী মেনে নেওয়ার জন্য
        yes | buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: oisuvedit-pro-app
        path: bin/*.apk
