name: Build Android APK with Buildozer
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Android Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          build-essential ccache git libffi-dev libssl-dev \
          libsqlite3-dev tcl-dev tk-dev libgdbm-dev libc6-dev \
          libbz2-dev zlib1g-dev openjdk-17-jdk unzip zip \
          autoconf automake libtool pkg-config patch altcpp

    - name: Install Python Tools
      run: |
        pip install --upgrade pip virtualenv
        pip install cython==0.29.33
        pip install kivy plyer ffpyplayer buildozer

    - name: Build Android APK
      run: |
        yes | buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: oisuvedit-app-debug
        path: bin/*.apk
